export const sampleUsers = [
  { _id: 1, name: 'Money Boy', age: 44, city: 'Wien', score: 821 },
  { _id: 2, name: 'Olaf Scholz', age: 67, city: 'Berlin', score: 92 },
  { _id: 3, name: 'Freddie Mercury', age: 79, city: 'London', score: 78 },
  { _id: 4, name: 'Alan Turing', age: 112, city: 'Manchester', score: 95 },
  { _id: 5, name: 'Alexander Marcus', age: 53, city: 'Berlin', score: 560 },
  { _id: 6, name: 'Donald Trump', age: 79, city: 'New York', score: 250 },
  { _id: 7, name: '50 Cent', age: 50, city: 'New York', score: 900 },
  { _id: 8, name: 'Albert Einstein', age: 146, city: 'Princeton', score: 110 },
  { _id: 9, name: 'Kollegah', age: 41, city: 'Düsseldorf', score: 790 },
  { _id: 10, name: 'Angela Merkel', age: 70, city: 'Berlin', score: 450 },
  { _id: 11, name: 'Elon Musk', age: 53, city: 'Austin', score: 950 },
  { _id: 12, name: 'Taylor Swift', age: 34, city: 'New York', score: 880 },
  { _id: 13, name: 'Cristiano Ronaldo', age: 39, city: 'Riyadh', score: 920 },
  { _id: 14, name: 'Lionel Messi', age: 37, city: 'Miami', score: 930 },
  { _id: 15, name: 'Marie Curie', age: 157, city: 'Paris', score: 105 },
  { _id: 16, name: 'Steve Jobs', age: 69, city: 'Cupertino', score: 840 },
  { _id: 17, name: 'Bill Gates', age: 69, city: 'Seattle', score: 780 },
  { _id: 18, name: 'Warren Buffett', age: 94, city: 'Omaha', score: 720 },
  { _id: 19, name: 'Mark Zuckerberg', age: 40, city: 'Palo Alto', score: 850 },
  { _id: 20, name: 'Jeff Bezos', age: 60, city: 'Seattle', score: 870 },
  { _id: 21, name: 'Oprah Winfrey', age: 70, city: 'Chicago', score: 750 },
  { _id: 22, name: 'Leonardo da Vinci', age: 572, city: 'Florence', score: 99 },
  { _id: 23, name: 'Pablo Picasso', age: 143, city: 'Barcelona', score: 88 },
  { _id: 24, name: 'Vincent van Gogh', age: 171, city: 'Amsterdam', score: 87 },
  { _id: 25, name: 'Wolfgang Amadeus Mozart', age: 268, city: 'Salzburg', score: 96 },
  { _id: 26, name: 'Ludwig van Beethoven', age: 254, city: 'Bonn', score: 94 },
  { _id: 27, name: 'Johann Sebastian Bach', age: 339, city: 'Leipzig', score: 97 },
  { _id: 28, name: 'Elvis Presley', age: 90, city: 'Memphis', score: 810 },
  { _id: 29, name: 'Michael Jackson', age: 66, city: 'Los Angeles', score: 940 },
  { _id: 30, name: 'Madonna', age: 66, city: 'New York', score: 760 },
  { _id: 31, name: 'Beyoncé', age: 43, city: 'Houston', score: 910 },
  { _id: 32, name: 'Rihanna', age: 36, city: 'Bridgetown', score: 830 },
  { _id: 33, name: 'Ed Sheeran', age: 33, city: 'London', score: 770 },
  { _id: 34, name: 'Adele', age: 36, city: 'London', score: 800 },
  { _id: 35, name: 'Bruno Mars', age: 39, city: 'Honolulu', score: 820 },
  { _id: 36, name: 'Drake', age: 38, city: 'Toronto', score: 860 },
  { _id: 37, name: 'Kanye West', age: 47, city: 'Chicago', score: 740 },
  { _id: 38, name: 'Jay-Z', age: 54, city: 'New York', score: 890 },
  { _id: 39, name: 'Eminem', age: 52, city: 'Detroit', score: 880 },
  { _id: 40, name: 'Snoop Dogg', age: 53, city: 'Los Angeles', score: 730 },
  { _id: 41, name: 'Dr. Dre', age: 59, city: 'Los Angeles', score: 850 },
  { _id: 42, name: 'Tupac Shakur', age: 53, city: 'Los Angeles', score: 920 },
  { _id: 43, name: 'Notorious B.I.G.', age: 52, city: 'New York', score: 910 },
  { _id: 44, name: 'Bob Marley', age: 79, city: 'Kingston', score: 870 },
  { _id: 45, name: 'John Lennon', age: 84, city: 'Liverpool', score: 890 },
  { _id: 46, name: 'Paul McCartney', age: 82, city: 'Liverpool', score: 860 },
  { _id: 47, name: 'George Harrison', age: 81, city: 'Liverpool', score: 780 },
  { _id: 48, name: 'Ringo Starr', age: 84, city: 'Liverpool', score: 720 },
  { _id: 49, name: 'David Bowie', age: 77, city: 'London', score: 850 },
  { _id: 50, name: 'Prince', age: 66, city: 'Minneapolis', score: 880 },
  { _id: 51, name: 'Kurt Cobain', age: 57, city: 'Seattle', score: 840 },
  { _id: 52, name: 'Jimi Hendrix', age: 82, city: 'Seattle', score: 900 },
  { _id: 53, name: 'Janis Joplin', age: 81, city: 'Port Arthur', score: 810 },
  { _id: 54, name: 'Jim Morrison', age: 81, city: 'Los Angeles', score: 790 },
  { _id: 55, name: 'Amy Winehouse', age: 41, city: 'London', score: 820 },
  { _id: 56, name: 'Whitney Houston', age: 61, city: 'Newark', score: 870 },
  { _id: 57, name: 'Aretha Franklin', age: 82, city: 'Detroit', score: 890 },
  { _id: 58, name: 'Frank Sinatra', age: 109, city: 'Hoboken', score: 830 },
  { _id: 59, name: 'Ella Fitzgerald', age: 107, city: 'Newport News', score: 850 },
  { _id: 60, name: 'Louis Armstrong', age: 123, city: 'New Orleans', score: 860 },
  { _id: 61, name: 'Miles Davis', age: 99, city: 'Alton', score: 880 },
  { _id: 62, name: 'John Coltrane', age: 98, city: 'Hamlet', score: 870 },
  { _id: 63, name: 'Charlie Parker', age: 104, city: 'Kansas City', score: 890 },
  { _id: 64, name: 'Billie Holiday', age: 109, city: 'Philadelphia', score: 840 },
  { _id: 65, name: 'Nina Simone', age: 91, city: 'Tryon', score: 820 },
  { _id: 66, name: 'Etta James', age: 86, city: 'Los Angeles', score: 810 },
  { _id: 67, name: 'Ray Charles', age: 94, city: 'Albany', score: 850 },
  { _id: 68, name: 'B.B. King', age: 99, city: 'Itta Bena', score: 830 },
  { _id: 69, name: 'Chuck Berry', age: 98, city: 'St. Louis', score: 800 },
  { _id: 70, name: 'Little Richard', age: 92, city: 'Macon', score: 790 },
  { _id: 71, name: 'Fats Domino', age: 96, city: 'New Orleans', score: 770 },
  { _id: 72, name: 'Jerry Lee Lewis', age: 89, city: 'Ferriday', score: 760 },
  { _id: 73, name: 'Johnny Cash', age: 92, city: 'Kingsland', score: 880 },
  { _id: 74, name: 'Willie Nelson', age: 91, city: 'Abbott', score: 750 },
  { _id: 75, name: 'Dolly Parton', age: 78, city: 'Sevierville', score: 820 },
  { _id: 76, name: 'Hank Williams', age: 101, city: 'Mount Olive', score: 810 },
  { _id: 77, name: 'Patsy Cline', age: 92, city: 'Winchester', score: 790 },
  { _id: 78, name: 'Loretta Lynn', age: 92, city: 'Butcher Hollow', score: 780 },
  { _id: 79, name: 'Tammy Wynette', age: 82, city: 'Itawamba County', score: 770 },
  { _id: 80, name: 'George Jones', age: 93, city: 'Saratoga', score: 800 },
  { _id: 81, name: 'Merle Haggard', age: 87, city: 'Oildale', score: 820 },
  { _id: 82, name: 'Waylon Jennings', age: 87, city: 'Littlefield', score: 810 },
  { _id: 83, name: 'Kris Kristofferson', age: 88, city: 'Brownsville', score: 790 },
  { _id: 84, name: 'Bob Dylan', age: 83, city: 'Duluth', score: 920 },
  { _id: 85, name: 'Bruce Springsteen', age: 75, city: 'Long Branch', score: 860 },
  { _id: 86, name: 'Tom Petty', age: 74, city: 'Gainesville', score: 840 },
  { _id: 87, name: 'Neil Young', age: 79, city: 'Toronto', score: 830 },
  { _id: 88, name: 'Eric Clapton', age: 79, city: 'Ripley', score: 870 },
  { _id: 89, name: 'Jimmy Page', age: 80, city: 'Heston', score: 880 },
  { _id: 90, name: 'Robert Plant', age: 76, city: 'West Bromwich', score: 850 },
  { _id: 91, name: 'Keith Richards', age: 81, city: 'Dartford', score: 820 },
  { _id: 92, name: 'Mick Jagger', age: 81, city: 'Dartford', score: 870 },
  { _id: 93, name: 'Roger Waters', age: 81, city: 'Great Bookham', score: 840 },
  { _id: 94, name: 'David Gilmour', age: 78, city: 'Cambridge', score: 860 },
  { _id: 95, name: 'Pete Townshend', age: 79, city: 'Chiswick', score: 830 },
  { _id: 96, name: 'Roger Daltrey', age: 80, city: 'Hammersmith', score: 810 },
  { _id: 97, name: 'Ozzy Osbourne', age: 76, city: 'Birmingham', score: 800 },
  { _id: 98, name: 'Tony Iommi', age: 76, city: 'Birmingham', score: 820 },
  { _id: 99, name: 'Lemmy Kilmister', age: 79, city: 'Stoke-on-Trent', score: 890 },
  { _id: 100, name: 'Slash', age: 59, city: 'Hampstead', score: 850 }
];
